const SET_IS_AUTH = 'SET_IS_AUTH';
const SET_IP_COUNTRY = 'SET_IP_COUNTRY';

const SET_DATES = 'SET_DATES';
const SET_TIME = 'SET_TIME';
const SET_SELECTED_CLEANING = 'SET_SELECTED_CLEANING';
const SET_SELECTED_SERVICES = 'SET_SELECTED_SERVICES';
const SET_APARTMENT_SIZE = 'SET_APARTMENT_SIZE';
const SET_SELECTED_SPEED = 'SET_SELECTED_SPEED';
const SET_BEDROOMS_NUM = 'SET_BEDROOMS_NUM';
const SET_BATHROOMS_NUM = 'SET_BATHROOMS_NUM';
const SET_KITCHENS_NUM = 'SET_KITCHENS_NUM';
const SET_DIRTY = 'SET_DIRTY';
const SET_ADDRESS1 = 'SET_ADDRESS1';
const SET_ADDRESS2 = 'SET_ADDRESS2';
const SET_POSTAL_CODE = 'SET_POSTAL_CODE';
const SET_CITY = 'SET_CITY';
const SET_PROVINCE = 'SET_PROVINCE';
const SET_INSTRUCTIONS = 'SET_INSTRUCTIONS';
const SET_SAVING = 'SET_SAVING';
const SET_CLEANING_SUM = 'SET_CLEANING_SUM';
const SET_EXTRAS_SUM = 'SET_EXTRAS_SUM';
const SET_SPEED_SUM = 'SET_SPEED_SUM';
const SET_TIME_SUM = 'SET_TIME_SUM';
const SET_SUBTOTAL = 'SET_SUBTOTAL';
const SET_IVA = 'SET_IVA';
const SET_TOTAL = 'SET_TOTAL';

export {
  SET_IS_AUTH,
  SET_IP_COUNTRY,
  SET_DATES,
  SET_TIME,
  SET_SELECTED_CLEANING,
  SET_SELECTED_SERVICES,
  SET_APARTMENT_SIZE,
  SET_SELECTED_SPEED,
  SET_BEDROOMS_NUM,
  SET_BATHROOMS_NUM,
  SET_KITCHENS_NUM,
  SET_DIRTY,
  SET_ADDRESS1,
  SET_ADDRESS2,
  SET_POSTAL_CODE,
  SET_CITY,
  SET_PROVINCE,
  SET_INSTRUCTIONS,
  SET_SAVING,
  SET_CLEANING_SUM,
  SET_EXTRAS_SUM,
  SET_SPEED_SUM,
  SET_TIME_SUM,
  SET_SUBTOTAL,
  SET_IVA,
  SET_TOTAL,
};
