const SET_IS_AUTH = 'SET_IS_AUTH';
const SET_IP_COUNTRY = 'SET_IP_COUNTRY';
const SET_USER = 'SET_USER';
const SET_ACTIVE_ORDERS = 'SET_ACTIVE_ORDERS';
const SET_PAST_ORDERS = 'SET_PAST_ORDERS';
const SET_ADDRESSES = 'SET_ADDRESSES';
const SET_UPDATED_ADDRESSES = 'SET_UPDATED_ADDRESSES';
const SET_OPENED_SUBSCRIPTION = 'SET_OPENED_SUBSCRIPTION';
const SET_OPENED_ORDER = 'SET_OPENED_ORDER';
const SET_JOBS = 'SET_JOBS';
const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';

const SET_CLEANING = 'SET_CLEANING';
const SET_REPEAT = 'SET_REPEAT';
const SET_DATE = 'SET_DATE';
const SET_TIME = 'SET_TIME';
const SET_DATES = 'SET_DATES';
const SET_ADD_EXCLUDED_DATES = 'SET_ADD_EXCLUDED_DATES';
const SET_EXCLUDED_DATES = 'SET_EXCLUDED_DATES';
const SET_CUSTOM_SCHEDULE = 'SET_CUSTOM_SCHEDULE';
const SET_DURATION = 'SET_DURATION';
const SET_START_DATE = 'SET_START_DATE';
const SET_LAST_DATE = 'SET_LAST_DATE';
const SET_SELECTED_CLEANING = 'SET_SELECTED_CLEANING';
const SET_SELECTED_SERVICES = 'SET_SELECTED_SERVICES';
const SET_ADDRESS_ID = 'SET_ADDRESS_ID';
const SET_APARTMENT_SIZE = 'SET_APARTMENT_SIZE';
const SET_SELECTED_SPEED = 'SET_SELECTED_SPEED';
const SET_LIVING_ROOMS_NUM = 'SET_LIVING_ROOMS_NUM';
const SET_BEDROOMS_NUM = 'SET_BEDROOMS_NUM';
const SET_BATHROOMS_NUM = 'SET_BATHROOMS_NUM';
const SET_KITCHENS_NUM = 'SET_KITCHENS_NUM';
const SET_DIRTY = 'SET_DIRTY';
const SET_ADDRESS1 = 'SET_ADDRESS1';
const SET_ADDRESS2 = 'SET_ADDRESS2';
const SET_POSTAL_CODE = 'SET_POSTAL_CODE';
const SET_CITY = 'SET_CITY';
const SET_PROVINCE = 'SET_PROVINCE';
const SET_INSTRUCTIONS = 'SET_INSTRUCTIONS';
const SET_SAVING = 'SET_SAVING';
const SET_CLEANING_SUM = 'SET_CLEANING_SUM';
const SET_EXTRAS_SUM = 'SET_EXTRAS_SUM';
const SET_SPEED_SUM = 'SET_SPEED_SUM';
const SET_TIME_SUM = 'SET_TIME_SUM';
const SET_SUBTOTAL = 'SET_SUBTOTAL';
const SET_IVA_PERCENT = 'SET_IVA_PERCENT';
const SET_IVA = 'SET_IVA';
const SET_TOTAL = 'SET_TOTAL';

const SET_SERVICES = 'SET_SERVICES';
const SET_EXTRA_SERVICES = 'SET_EXTRA_SERVICES';
const SET_PRICING = 'SET_PRICING';
const SET_TIME_PRICING = 'SET_TIME_PRICING';
const SET_CLEANING_PRICING = 'SET_CLEANING_PRICING';
const SET_SQM_PRICING = 'SET_SQM_PRICING';

export {
  SET_IS_AUTH,
  SET_IP_COUNTRY,
  SET_USER,
  SET_ACTIVE_ORDERS,
  SET_PAST_ORDERS,
  SET_ADDRESSES,
  SET_UPDATED_ADDRESSES,
  SET_OPENED_SUBSCRIPTION,
  SET_OPENED_ORDER,
  SET_JOBS,
  SET_ACTIVE_TAB,
  SET_CLEANING,
  SET_REPEAT,
  SET_DATE,
  SET_TIME,
  SET_DATES,
  SET_ADD_EXCLUDED_DATES,
  SET_EXCLUDED_DATES,
  SET_CUSTOM_SCHEDULE,
  SET_DURATION,
  SET_START_DATE,
  SET_LAST_DATE,
  SET_SELECTED_CLEANING,
  SET_SELECTED_SERVICES,
  SET_ADDRESS_ID,
  SET_APARTMENT_SIZE,
  SET_SELECTED_SPEED,
  SET_LIVING_ROOMS_NUM,
  SET_BEDROOMS_NUM,
  SET_BATHROOMS_NUM,
  SET_KITCHENS_NUM,
  SET_DIRTY,
  SET_ADDRESS1,
  SET_ADDRESS2,
  SET_POSTAL_CODE,
  SET_CITY,
  SET_PROVINCE,
  SET_INSTRUCTIONS,
  SET_SAVING,
  SET_CLEANING_SUM,
  SET_EXTRAS_SUM,
  SET_SPEED_SUM,
  SET_TIME_SUM,
  SET_SUBTOTAL,
  SET_IVA_PERCENT,
  SET_IVA,
  SET_TOTAL,
  SET_SERVICES,
  SET_EXTRA_SERVICES,
  SET_PRICING,
  SET_TIME_PRICING,
  SET_CLEANING_PRICING,
  SET_SQM_PRICING,
};
